baseURL = "https://gohugo.io"
title = "栄言記集"
theme = 'PhunBlog'
author = "kaeru2193"
copyright = "©　二〇二三　之機"
paginate = 3
languageCode = "pn"
DefaultContentLanguage = "pn"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]
  disableComments=true
  images = ["ogp/image.png"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "我事"
    url = "/about-me/"
    weight = 10
  [[menu.main]]
    identifier = "home"
    name = "庵"
    url = "/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
